const images = {
  LOTIT: require("./image1.png"),
  KEYTIP: require("./keytip.png"),
  HOME: require("./home.png"),
  HOMEON: require("./homon.png"),
  NETWORK: require("./network.png"),
  NETWORKON: require("./networkon.png"),
  POST: require("./post.png"),
  FEED: require("./feed.png"),
  FEEDON: require("./feedon.png"),
  DEALS: require("./deals.png"),
  DEALSON: require("./dealson.png"),
  GGLOGIN: require("./icon-gg__login.webp"),
  JOINLOG: require("./image27.png"),
  IMG3: require("./image3.png"),
  BACK: require("./back.png"),
  VERI: require("./image22.png"),
  SETPIC: require("../images/image6.png"),
  OPEN_VALUE: require("../images/openValue.png"),
  GHIM: require("../images/ghim.png"),
  SEND: require("../images/send.png"),
  OPTIONS: require("../images/options.png"),
  GROUPS: require("./groups.png"),
  CLEAN: require("./clean.png"),

  // HOME_ACTIVE: require("./icons/homeActive.png"),
  LOGO: require("./logo.png"),
  ICONCHAT: require("./icons/iconChat.png"),
  ICONNOTIF: require("./icons/iconNotif.png"),
  ICONSNOTIF2: require("./icons/iconsNotif2.png"),
  BANER: require("./baner.png"),
  IMAGE: require("./image.png"),
  SHARE: require("./icons/share.png"),
  COMMENT: require("./icons/comment.png"),
  LIKE: require ("./icons/like.png"),
  CALENDAR: require ("./icons/calendar.png"),
  IMG: require ("./img.png"),
  SUGGESTION: require ("./icons/suggestion.png"),
  CONTACTS: require ("./icons/contacts.png"),
  IMGAVT: require ("./imgavt.png"),
  IMGAVT2: require ("./imgavt2.png"),
  IMGAVT3: require ("./imgavt3.png"),
  IMGAVT4: require ("./imgavt4.png"),
  IMGAVT5: require ("./imgavt5.png"),
  IMGAVT6: require ("./imgavt6.png"),
  NEWNOTIF: require ("./newnotif.png"),
  MATCHES1: require ("./matches1.png"),
  MATCHES2: require ("./matches2.png"),
  COSMETICS: require ("./cosmetics.png"),
  CARS: require ("./cars.png"),
  REALESTATE: require ("./realestate.png"),
  HEALTHCARE: require ("./healthcare.png"),
  AVATA: require ("./avata.png"),
  IMGBIA: require ("./imgbia.png"),
  IMGBANTIN: require ("./imgbantin.png"),
  MORE: require ("./more.png"),
  EVENTS: require("./events.png"),
  NEWS: require("./news.png"),
  SETTINGS: require("./settings.png"),
  LOGOUT: require("./logout.png"),
};
export default images;
